 

CREATE TABLE MgrS_LAM.MEARS_SURNAME as (
sel ind.party_id as party_id, ind.LastName as Surname, udpr.UDPRN as UDPRN, sum(udpr.ItemCount) as ItemCount, sum(udpr.SubCount) as SubCount 
from
MgrS_LAM.MEARS_UDPRN udpr
Inner Join 
 EDW_SCVER_CODA_ACCS_VIEWS.V_INDIVIDUAL ind
on udpr.party_id =  ind.party_id
group by 1,2, 3
) with data
;


sel top 100* from
EDW_SCVER_CODA_ACCS_VIEWS.V_INDIVIDUAL;


sel top 100 * from
MgrS_LAM.MEARS_UDPRN
;


sel count (*)
from 
MgrS_LAM.MEARS_SURNAME ;

sel top 100* from 
MgrS_LAM.MEARS_SURNAME ;


sel top  100 *
from 
MgrS_LAM.MEARS_SURNAME 
WHERE SURNAME NOT LIKE '%UNKNOWN%'
/*Removing Surnames of common words found in business names that are NOT Surnames*/
AND SURNAME NOT LIKE '%SERVICE%' AND SURNAME NOT LIKE '%ACADEMY%' AND SURNAME NOT LIKE '%INDUSTRIE%' AND SURNAME NOT LIKE '%CONTRACT%'
AND SURNAME NOT LIKE '%PROPERT%' AND SURNAME NOT LIKE '%ACCOUNT%' AND SURNAME NOT LIKE '%COMMUNICATION%' AND SURNAME NOT LIKE '%SOLUTION%'
AND SURNAME NOT LIKE '%COMPANY%' AND SURNAME NOT LIKE '%ELECTRONI%' AND SURNAME NOT LIKE '%ENTERTAIN%' AND SURNAME NOT LIKE '%CONSULT%'
AND SURNAME NOT LIKE '%ACCESSO%' AND SURNAME NOT LIKE '%INTERIOR%' AND SURNAME NOT LIKE '%THERAPIES%'
AND SURNAME NOT LIKE '%INVESTMENT%' AND SURNAME NOT LIKE '%SOLICITOR%' AND SURNAME NOT LIKE '%ADVENTURES%'
/*Removing Surnames with numbers in them*/
AND SURNAME NOT LIKE '%0%' AND SURNAME NOT LIKE '%1%' AND SURNAME NOT LIKE '%2%' AND SURNAME NOT LIKE '%3%' AND SURNAME NOT LIKE '%4%'
AND SURNAME NOT LIKE '%5%' AND SURNAME NOT LIKE '%6%' AND SURNAME NOT LIKE '%7%' AND SURNAME NOT LIKE '%8%' AND SURNAME NOT LIKE '%9%'
/*Removing Surnames with common email address parts*/
AND SURNAME NOT LIKE '%GMAIL%' AND SURNAME NOT LIKE '%GOOGLEMAIL%' AND SURNAME NOT LIKE '%OUTLOOK%' AND SURNAME NOT LIKE '%HOTMAIL%' AND SURNAME NOT LIKE '%YAHOOCOM%'
AND SURNAME NOT LIKE '%NTLWORLD%' AND SURNAME NOT LIKE '%TISCALICOUK%' AND SURNAME NOT LIKE '%OPENWORLD%' AND SURNAME NOT LIKE '%TELECOM%'
/*Removing Surnames with more than 3 repeating consecutive characters*/
AND SURNAME NOT LIKE '%AAA%' AND SURNAME NOT LIKE '%BBB%' AND SURNAME NOT LIKE '%CCC%' AND SURNAME NOT LIKE '%DDD%' AND SURNAME NOT LIKE '%EEE%' 
AND SURNAME NOT LIKE '%FFF%' AND SURNAME NOT LIKE '%GGG%' AND SURNAME NOT LIKE '%HHH%' AND SURNAME NOT LIKE '%III%' AND SURNAME NOT LIKE '%JJJ%' 
AND SURNAME NOT LIKE '%KKK%' AND SURNAME NOT LIKE '%LLL%' AND SURNAME NOT LIKE '%MMM%' AND SURNAME NOT LIKE '%NNN%' AND SURNAME NOT LIKE '%OOO%' 
AND SURNAME NOT LIKE '%PPP%' AND SURNAME NOT LIKE '%QQQ%' AND SURNAME NOT LIKE '%RRR%' AND SURNAME NOT LIKE '%SSS%' AND SURNAME NOT LIKE '%TTT%' 
AND SURNAME NOT LIKE '%UUU%' AND SURNAME NOT LIKE '%VVV%' AND SURNAME NOT LIKE '%WWW%' AND SURNAME NOT LIKE '%XXX%' AND SURNAME NOT LIKE '%YYY%' 
AND SURNAME NOT LIKE '%ZZZ%' 
/*Removing SURNAMES = PREFIX OR STARTING WITH MRS*/
AND SURNAME <> 'DOCTOR' AND SURNAME <> 'MR' AND SURNAME <> 'MS' AND SURNAME <> 'MISTER' AND SURNAME <> 'MISS' AND SURNAME <> 'DR'  AND SURNAME <> 'AUNT' AND SURNAME <> 'UNCLE'
AND SURNAME NOT LIKE 'MRS%'
/*Removing Surnames with only one character or where the surname exceeds 25 characters*/
AND CHARACTER_LENGTH (SURNAME) >1 AND CHARACTER_LENGTH (SURNAME) < 26;




